# MobileVLCKit is the embedded VLC engine. CocoaPods is the most reliable way to add it.
# After creating the Xcode project (see README), run:  pod install
# then always open  Media26.xcworkspace  (NOT the .xcodeproj).

platform :ios, '13.0'

target 'Media26' do
  use_frameworks!
  pod 'MobileVLCKit', '~> 3.6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
